
## ╔═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
## ║ Layer 01 ❱ Basic Shell Environment
## ╚═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════

include './Shell.Brewfile', opional: false

include './Terminal.Brewfile', optional: false

include './GnuUtils.Brewfile', optional: false

include './MoreUtils.Brewfile', optional: false

include './Security.Brewfile', optional: false

include './Editors.Brewfile', optional: false

include './Text.Brewfile', optional: false
