
## ╔═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
## ║ Layer 04 ❱ Development Tools
## ╚═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════

include './Common.Brewfile', optional: false

include './Testing.Brewfile', optional: false

include './Language.Brewfile', optional: false

include './IDE.Brewfile', optional: false

include './Agentic.Brewfile', optional: false

include './Database.Brewfile', optional: false

