[tools]
rust = "latest"

"cargo:bacon" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:cargo-cache" = "latest"
"cargo:cargo-deny" = "latest"
"cargo:cargo-depgraph" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-expand" = "latest"
"cargo:flamegraph" = "latest"
"cargo:cargo-generate" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-outdated" = "latest"
"cargo:cargo-shear" = "latest"
"cargo:cargo-tarpaulin" = "latest"
"cargo:cargo-udeps" = "latest"
"cargo:cargo-update" = "latest"
"cargo:cargo-watch" = "latest"
"cargo:dioxus-cli" = "latest"
"cargo:release-plz" = "latest"
"cargo:wasm-bindgen-cli" = "latest"

taplo = "latest"
