"$schema" = 'https://starship.rs/config-schema.json'

format = """
[┌─┤ ](dimmed)\
$directory\
$git_branch\
$git_status\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$package\
$docker_context\
$aws\
$gcloud\
[├](dimmed)\
$fill\
[┤ ](dimmed)\
$status\
$sudo\
$shlvl\
$jobs\
$cmd_duration\
$time\
[│](dimmed)\
$line_break\
$character"""

add_newline = true
continuation_prompt = "[└┈┈](dimmed)"

[fill]
symbol = "┈"
style = "dimmed"

[character]
success_symbol = '[└─](dimmed) [❯](bold green)'
error_symbol = '[└─](dimmed) [❯](bold red)'

[status]
disabled = false
format = '[$symbol( $common_meaning)( $signal_name)( $signal_number)( $maybe_int) ]($style)'
style = 'fg:red bg:color_bg'
success_style = 'bold fg:green bg:color_bg'
symbol = '✘'
map_symbol = false
pipestatus = true
pipestatus_format = '[$pipestatus]($style)'

[time]
disabled = false
format = '[⏲](bold) [$time]($style) '
time_format = '%T'
utc_time_offset = '-5'

[aws]
symbol = "[](fg:orange) "
style = "orange"

[gcloud]
symbol = "[](fg:blue) "
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
style = "blue"

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[conda]
symbol = " "
disabled = true

[docker_context]
symbol = " "
only_with_files = true

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

# [haskell]
# symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "
style = "bold dimmed green"
threshold = 75
disabled = false

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[custom.racket]
description = "Racket"
symbol = "𝝺 "
style = "bold blue"
extensions = ["rkt", "scrbl"]
command = """racket --version | cut -d "v" -f 2 | cut -d " " -f 1"""
format = "via [$symbol($output )]($style) "

[custom.os-macos]
symbol = " "
when = """ test `uname -s` = "Darwin" """

[custom.os-linux]
symbol = " "
when = """ test `uname -s` = "Linux" """

[custom.os-windows]
symbol = " "
when = """ test `uname -s` = "Windows" """

