
## ╔═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
## ║ Layer 02 ❱ System Integration
## ╚═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════

cask 'console'                          # A better console tool

mas 'Screens 5: VNC Remote Desktop', id: 1663047912

include './Sync.Brewfile', optional: false

include './Containers.Brewfile', optional: false

include './Fonts.Brewfile', optional: false
