
## ╔═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
## ║ Layer 05 ❱ Personal Apps
## ╚═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════

include './Synthesizer.Brewfile', optional: false

include './Ham.Brewfile', optional: false

include './Diving.Brewfile', optional: false

include './Other.Brewfile', optional: false
